### ISSUE TITLE
Additional changes to documentation

### ISSUE THREAD

**Issue by pravsripad** [Cogitate-consortium/cogitate-msp1#8]
- [x] Add MSP to documentation next to Cogitate Main Scientific Paper 1
- [x] check with Nico on PR merge security policy
- [x] add link to preregistration (it is still not open but include the link anyway) (https://osf.io/3t7ax/)

**Comment by pravsripad** [comment]
@nbonacchi can we limit PRs into this repo to only the members from this organization?

**Comment by nbonacchi** [comment]
We can limit who can approve merges and protect branches so that changes can only be merged with a PR. I don't think it's possible to limit PRs only to members of the repo, the whole point of PRs is to accept contributions. We can and should close and comment on PRs that are out of scope or that we don't think we should integrate.

**Comment by pravsripad** [comment]
I think that since this is code for a paper we wouldn't want any PRs at all except if it contains changes made via contributions to msp1. 

I guess limiting merges and protecting the branches should suffice. Can you please activate this and limit it to only those who have contributed to the repo so far? Thanks.

**Comment by nbonacchi** [comment]
Done! main branch is now locked i.e. read only to users, PRs need to be approved by at least one contribuitor to be merged into main

**Comment by nbonacchi** [comment]
I'll test to see if it works as expected

**Comment by nbonacchi** [comment]
OK it seems that it works as expected, direct commits to master do not work, you have to create a branch and make a PR, I also removed the ability of force pushing/rewriting history
Let's keep an eye on the next PR to see if it all works as expected. 
Ofc that owners and Maintainers (so everyone contributing code) can always bypass the rules by removing the protection rules temporarily but that means you ought to really know what you are doing.
